version: '3.8'

services:
  instadl-app:
    image: ghcr.io/hariomop12/insta-reel-downloder:latest
    container_name: instadl-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME:-reels}
      - R2_ENDPOINT=${R2_ENDPOINT}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8080}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: instadl-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
    depends_on:
      - instadl-app
    restart: unless-stopped

networks:
  default:
    name: instadl-network