name = "insta-reel-downloader"
pages_build_output_dir = "."
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "REELS_BUCKET"
bucket_name = "chatappfiles"
